databases:
  - name: foodie-friends
    databaseName: foodie-friends-prod
    user: foodie-friends

services:
  - type: web
    name: foodie-friends
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: foodie-friends
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
