databases:
  - name: foodiefriends

services:
  - type: redis
    name: cache
    ipAllowList: []
    maxmemoryPolicy: allkeys-lfu
  - type: web
    name: foodie-friends
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: foodie-friends
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: REDIS_URL
        fromService:
          type: redis
          name: cache
          property: connectionString
